version: '2'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: mysql-wmx:5.6.38
    container_name: mysql-wmx
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - $PWD/container_data/mysql:/var/lib/mysql

  base_wmx:
    build:
      context: .
      dockerfile: Dockerfile-base
    image: base-wmx:latest
    container_name: base-wmx

  hive:
    build:
      context: .
      dockerfile: Dockerfile-hive
    image: hive-wmx:2.0.1
    container_name: hive-wmx
    ports:
     - "10000:10000"
    volumes:
     - $PWD/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
     - $PWD/data/hive/warehouse:/data/hive/warehouse
     - $PWD/data/table_data:/data/shared/table_data
    links:
     - "mysql:mysql"

  spark:
    build:
      context: .
      dockerfile: Dockerfile-spark
    image: spark-wmx:2.2.0
    container_name: spark-wmx
    ports:
     - "14040:4040"
     - "18080:8080"
    volumes:
     - $PWD/conf/hive-site.xml:/opt/spark/conf/hive-site.xml
     - $PWD/conf/spark/log4j.properties:/opt/spark/conf/log4j.properties
     - $PWD/data/spark/warehouse:/data/shared/hive/warehouse
     - $PWD/data/table_data:/data/shared/table_data
    links:
      - "mysql:mysql"
    command: tail -F anything
