FROM base-wmx:latest

ENV SPARK_VERSION=2.4.5
ENV SPARK_HOME=/opt/spark
ENV SPARK_CONF_DIR=$SPARK_HOME/conf
ENV PATH $PATH:$SPARK_HOME/bin


RUN curl -sL \
  "https://archive.apache.org/dist/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop2.7.tgz" \
  -o spark-$SPARK_VERSION-bin-hadoop2.7.tgz

RUN tar -xf spark-$SPARK_VERSION-bin-hadoop2.7.tgz -C /opt/ \
  && ln -s /opt/spark-$SPARK_VERSION-bin-hadoop2.7 $SPARK_HOME \
  && mkdir -p /data/spark/ \
  && mkdir -p $SPARK_CONF_DIR \
  && mkdir -p /data/shared/ \
  && chown -R root:root $SPARK_HOME \
  && chown -R root:root /opt/spark-$SPARK_VERSION-bin-hadoop2.7


# -- install MySQL client jar for Spark

RUN wget https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-java-5.1.45.tar.gz
RUN tar xf mysql-connector-java-5.1.45.tar.gz
RUN mv mysql-connector-java-5.1.45/mysql-connector-java-5.1.45-bin.jar $SPARK_HOME/jars
RUN rm -rf mysql-connector-java-5.1.45
