FROM base-wmx:latest

# -- Hadoop Conf
ENV HADOOP_VERSION=2.7.4
ENV HADOOP_HOME=/opt/hadoop
ENV HADOOP_CONF_DIR=$HADOOP_HOME/conf

# -- Hive Conf
ENV HIVE_VERSION=2.0.1
ENV HIVE_HOME=/opt/hive
ENV HIVE_CONF_DIR=$HIVE_HOME/conf

ENV PATH $PATH:$HADOOP_HOME/bin:$HIVE_HOME/bin


# -- install Hadoop

RUN curl -sL \
  "https://archive.apache.org/dist/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz" \
  | gunzip \
  | tar -x -C /opt/

RUN ln -s /opt/hadoop-$HADOOP_VERSION $HADOOP_HOME
RUN rm -rf $HADOOP_HOME/share/doc

RUN chown -R root:root $HADOOP_HOME \
&& mkdir -p $HADOOP_HOME/logs \
&& mkdir -p $HADOOP_CONF_DIR \
&& chmod 777 $HADOOP_CONF_DIR \
&& chmod 777 $HADOOP_HOME/logs



# -- install Hive

RUN curl -sL \
  "https://archive.apache.org/dist/hive/hive-$HIVE_VERSION/apache-hive-$HIVE_VERSION-bin.tar.gz" \
    | gunzip \
    | tar -x -C /opt/

RUN ln -s /opt/apache-hive-$HIVE_VERSION-bin $HIVE_HOME

RUN chown -R root:root $HIVE_HOME \
  && mkdir -p $HIVE_HOME/hcatalog/var/log \
  && mkdir -p $HIVE_HOME/var/log \
  && mkdir -p $HIVE_HOME/lib \
  && mkdir -p /data/hive/ \
  && mkdir -p /data/shared \
  && mkdir -p $HIVE_CONF_DIR \
  && chmod 777 $HIVE_HOME/hcatalog/var/log \
  && chmod 777 $HIVE_HOME/var/log \
  && chmod 777 $HIVE_HOME/lib



# -- install MySQL client jar for Hive

  RUN wget https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-java-5.1.45.tar.gz
  RUN tar xf mysql-connector-java-5.1.45.tar.gz
  RUN mv mysql-connector-java-5.1.45/mysql-connector-java-5.1.45-bin.jar $HIVE_HOME/lib
  RUN rm -rf mysql-connector-java-5.1.45
